# Generated by Django 3.1.7 on 2021-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, unique=True)),
                ('receiver', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('txhash', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
