# Generated by Django 3.1.7 on 2021-02-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField()),
                ('transaction_list', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.BooleanField()),
                ('merkle_root', models.CharField(blank=True, max_length=255, unique=True)),
                ('block_hash', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
