# Generated by Django 3.1.7 on 2021-02-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('merkle_root', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('block_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
