# Generated by Django 3.1.7 on 2021-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('available', models.FloatField()),
                ('balance_local', models.FloatField()),
                ('available_local', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
